import { Router, type IRouter } from "express";
import healthRouter from "./health";
import courtsRouter from "./courts";
import seasonsRouter from "./seasons";
import programsRouter from "./programs";
import leaguesRouter from "./leagues";
import campsRouter from "./camps";
import dropinsRouter from "./dropins";
import dropinTemplatesRouter from "./dropinTemplates";
import tournamentsRouter from "./tournaments";
import registrationsRouter from "./registrations";
import teamsRouter from "./teams";
import usersRouter from "./users";
import adminRouter from "./admin";
import venuesRouter from "./venues";
import ageGroupsRouter from "./ageGroups";
import guardiansRouter from "./guardians";
import staffProfilesRouter from "./staffProfiles";
import auditLogRouter from "./auditLog";
import ageGroupMappingsRouter from "./ageGroupMappings";
import playerProfilesRouter from "./playerProfiles";
import pricingRulesRouter from "./pricingRules";
import facilitySplitRulesRouter from "./facilitySplitRules";
import serviceFeeConfigRouter from "./serviceFeeConfig";
import revenueRecordsRouter from "./revenueRecords";
import checkoutRouter from "./checkout";
import discountCodesRouter from "./discountCodes";
import refundPoliciesRouter from "./refundPolicies";
import accountCreditsRouter from "./accountCredits";
import paymentsRouter from "./payments";
import installmentsRouter from "./installments";
import depositBalanceRouter from "./depositBalance";
import cancellationEngineRouter from "./cancellationEngine";
import stripeConnectRouter from "./stripeConnect";
import adminPayoutsRouter from "./adminPayouts";
import aiCalendarsRouter from "./aiCalendars";
import aiSchedulingRouter from "./aiScheduling";
import aiProposalsRouter from "./aiProposals";
import assistantRouter from "./assistant";
import notificationPreferencesRouter from "./notificationPreferences";
import subRefAlertsRouter from "./subRefAlerts";
import playerStatsRouter from "./playerStats";
import seasonRecapsRouter from "./seasonRecaps";
import familyDashboardRouter from "./familyDashboard";
import courtAvailabilityRouter from "./courtAvailability";
import incidentReportsRouter from "./incidentReports";
import fixtureOpsRouter from "./fixtureOps";
import insuranceTrackingRouter from "./insuranceTracking";
import privacyControlsRouter from "./privacyControls";
import membershipsRouter from "./memberships";
import referralsRouter from "./referrals";
import adminReportsRouter from "./adminReports";
import attendanceHistoryRouter from "./attendanceHistory";
import checkinRouter from "./checkin";
import gameCardsRouter from "./gameCards";
import gameEventsRouter from "./gameEvents";
import trainingRouter from "./training";
import aiCreationAgentRouter from "./aiCreationAgent";
import invitesRouter from "./invites";
import teamInvitesRouter from "./teamInvites";
import waiversRouter from "./waivers";
import devEmailPreviewRouter from "./devEmailPreview";
import adminUsersRouter from "./adminUsers";
import ageGroupWaiversRouter from "./ageGroupWaivers";
import messagingRouter from "./messaging";
import notificationsInboxRouter from "./notificationsInbox";
import kotcRouter from "./kotc";

const router: IRouter = Router();

router.use(healthRouter);
router.use(courtsRouter);
router.use(seasonsRouter);
router.use(programsRouter);
router.use(leaguesRouter);
router.use(campsRouter);
// Backward-compatible path aliases: /dropins/templates/* → /dropin-templates/*
// and /dropins/occurrences/* → /dropin-occurrences/*. Must run BEFORE dropinsRouter
// so it intercepts the more-specific prefixes before /dropins/* matches them.
router.use((req, _res, next) => {
  if (req.url.startsWith("/dropins/templates")) {
    req.url = req.url.replace("/dropins/templates", "/dropin-templates");
  } else if (req.url.startsWith("/dropins/occurrences")) {
    req.url = req.url.replace("/dropins/occurrences", "/dropin-occurrences");
  }
  next();
});
router.use(dropinsRouter);
router.use(tournamentsRouter);
router.use(registrationsRouter);
router.use(teamsRouter);
router.use(usersRouter);
router.use(adminRouter);
router.use(venuesRouter);
router.use(ageGroupsRouter);
router.use(guardiansRouter);
router.use(staffProfilesRouter);
router.use(auditLogRouter);
router.use(ageGroupMappingsRouter);
router.use(playerProfilesRouter);
router.use(pricingRulesRouter);
router.use(facilitySplitRulesRouter);
router.use(serviceFeeConfigRouter);
router.use(revenueRecordsRouter);
router.use(checkoutRouter);
router.use(discountCodesRouter);
router.use(refundPoliciesRouter);
router.use(accountCreditsRouter);
router.use(paymentsRouter);
router.use(installmentsRouter);
router.use(depositBalanceRouter);
router.use(cancellationEngineRouter);
router.use(stripeConnectRouter);
router.use(adminPayoutsRouter);
router.use(aiCalendarsRouter);
router.use(aiSchedulingRouter);
router.use(aiProposalsRouter);
router.use(assistantRouter);
router.use(notificationPreferencesRouter);
router.use(subRefAlertsRouter);
router.use(playerStatsRouter);
router.use(seasonRecapsRouter);
router.use(familyDashboardRouter);
router.use(courtAvailabilityRouter);
router.use(incidentReportsRouter);
router.use(fixtureOpsRouter);
router.use(insuranceTrackingRouter);
router.use(privacyControlsRouter);
router.use(membershipsRouter);
router.use(referralsRouter);
router.use(adminReportsRouter);
router.use(attendanceHistoryRouter);
router.use(checkinRouter);
router.use(gameCardsRouter);
router.use(gameEventsRouter);
router.use(trainingRouter);
router.use(aiCreationAgentRouter);
router.use(invitesRouter);
router.use(teamInvitesRouter);
router.use(waiversRouter);
router.use(devEmailPreviewRouter);
router.use(adminUsersRouter);
router.use(ageGroupWaiversRouter);
router.use(messagingRouter);
router.use(notificationsInboxRouter);
router.use(dropinTemplatesRouter);
router.use(kotcRouter);

export default router;
